site_name: ""
repo_url: https://github.com/moonshinerd/sexto-andar-api
      
extra_css:
  - assets/stylesheets/style.css

nav:
  - Home: index.md
  - Backlog: 
    - Histórias de Usuário: backlog/userStories.md
  - Arquitetura:
    - Arquitetura Selecionada: arquitetura/arquitetura-selecionada.md
    - Tecnologias Utilizadas: arquitetura/tecnologias.md

theme:
  logo: assets/logo.png
  name: material
  font:
    text: IBM Plex Serif
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
  palette:
    - scheme: default
      primary: green
      accent: white
      toggle:
        icon: material/weather-night
        name: Trocar para modo escuro

    - scheme: slate
      primary: green
      accent: white
      toggle:
        icon: material/weather-sunny
        name: Trocar para modo claro
  icon:
    repo: fontawesome/brands/github


markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true