site_name: ""
repo_url: https://github.com/moonshinerd/sexto-andar-api
      
extra_css:
  - stylesheets/style.css

nav:
  - Home: index.md
  - Atas:
    - Ata 1: Atas/ata01.md
    - Ata 2: Atas/ata02.md
    - Ata 3: Atas/ata03.md

theme:
  logo: assets/logo.png
  name: material
  font:
    text: IBM Plex Serif
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
  palette:
    - scheme: default
      primary: green
      accent: white
      toggle:
        icon: material/weather-night
        name: Trocar para modo escuro

    - scheme: slate
      primary: blue
      accent: white
      toggle:
        icon: material/weather-sunny
        name: Trocar para modo claro
  icon:
    repo: fontawesome/brands/github


markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true